version: '3'

services:
  app:
    container_name: user-service-app
    image: golang:1.17.2-stretch
    command: ["sh", "-c", "go mod download && go run main.go"]
    ports:
      - '2020:2020'
    environment:
      - PORT=2020
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongodb

  mongodb:
    container_name: user-service-mongodb
    image: mongo:5.0.3
    ports:
      - '27117:27017'
    volumes:
      - /microservice-volumes/user-service/mongodb:/data/db