// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	users "github.com/wisdommatt/ecommerce-microservice-user-service/internal/users"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, newUser
func (_m *UserService) CreateUser(ctx context.Context, newUser *users.User) (*users.User, error) {
	ret := _m.Called(ctx, newUser)

	var r0 *users.User
	if rf, ok := ret.Get(0).(func(context.Context, *users.User) *users.User); ok {
		r0 = rf(ctx, newUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *users.User) error); ok {
		r1 = rf(ctx, newUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserFromJWT provides a mock function with given fields: ctx, jwtToken
func (_m *UserService) GetUserFromJWT(ctx context.Context, jwtToken string) (*users.User, error) {
	ret := _m.Called(ctx, jwtToken)

	var r0 *users.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *users.User); ok {
		r0 = rf(ctx, jwtToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jwtToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx, afterId, limit
func (_m *UserService) GetUsers(ctx context.Context, afterId string, limit int32) ([]users.User, error) {
	ret := _m.Called(ctx, afterId, limit)

	var r0 []users.User
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) []users.User); ok {
		r0 = rf(ctx, afterId, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int32) error); ok {
		r1 = rf(ctx, afterId, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginUser provides a mock function with given fields: ctx, email, password
func (_m *UserService) LoginUser(ctx context.Context, email string, password string) (*users.User, string, error) {
	ret := _m.Called(ctx, email, password)

	var r0 *users.User
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *users.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
